repos:

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    args: [
      --force-exclude, src/ansys/templates/python,
      --line-length, "100",
      src, tests
    ]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    exclude: ^src/ansys/templates/pypkg/
    args: [
      --profile, black,
      --force-sort-within-sections,
      --line-length, "100",
      --section-default, THIRDPARTY, 
      --skip-glob, src/ansys/templates/python/*, 
      --filter-files,
      tests, doc
    ]

- repo: https://gitlab.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: [
      tests,
    ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: ^src/ansys/templates/python/|^tests
