[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
# Check https://python-poetry.org/docs/pyproject/ for all available sections
name = "ansys-product-library"
version = "0.1.dev0"
description = "A python wrapper for ansys product library"
license = "MIT"
authors = ["ANSYS, Inc. <ansys.support@ansys.com>"]
maintainers = ["PyAnsys developers <pyansys.maintainers@ansys.com>"]
readme = "README.rst"
repository = "https://github.com/pyansys/pyproduct-library"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [
    { include = "ansys", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
importlib-metadata = {version = "^4.0", python = "<3.8"}

# Optional documentation dependencies
Sphinx = {version = "==5.1.1", optional = true}
numpydoc = {version = "==1.4.0", optional = true}
ansys-sphinx-theme = {version = "==0.4.2", optional = true}
sphinx-copybutton = {version = "==0.5.0", optional = true}

# Optional testing dependencies
pytest = {version = "==7.1.2", optional = true}
pytest-cov = {version = "==3.0.0", optional = true}

# Optional build requirements
build = {version = "==0.8.0", optional = true}
twine = {version = "==4.0.1", optional = true}

[tool.poetry.extras]
dist = ["build", "twine"]
tests = ["pytest", "pytest-cov"]
doc = ["Sphinx", "numpydoc", "ansys-sphinx-theme", "sphinx-copybutton"]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 100
default_section = "THIRDPARTY"
src_paths = ["doc", "src", "tests"]

[tool.coverage.run]
source = ["ansys.product"]

[tool.coverage.report]
show_missing = true
