version: '3.9'

services:

  library:
    image: project/library
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    stdin_open: true
    tty: true
    networks:
      - project





networks:
  project:
    name: project-stream