name: GitHub CI
on:
  pull_request:
  push:

env:
  MAIN_PYTHON_VERSION : '3.10'
  LIBRARY_NAME: 'ansys-templates'
  CNAME: 'templates.ansys.com'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: "Run PyAnsys code style checks"
        uses: pyansys/actions/code-style@main

  doc-style:
    name: Doc style
    runs-on: ubuntu-latest
    steps:
      - name: "Run Ansys documentation style checks"
        uses: pyansys/actions/doc-style@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  doc-build:
    name: "Building documentation"
    runs-on: ubuntu-latest
    needs: doc-style
    steps:
      - name: "Run Ansys documentation building action"
        uses: pyansys/actions/doc-build@main

  doc-deploy-stable:
    name: "Deploy stable documentation"
    runs-on: ubuntu-latest
    needs: doc-build
    steps:
      - name: "Deploy the stable documentation"
        uses: pyansys/actions/doc-deploy-stable@main
        with:
            cname: ${{ env.CNAME }}
            token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: Smoke tests
    needs: code-style
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        cfg:
          - {python-version: "3.7", toxenv: "py37"}
          - {python-version: "3.8", toxenv: "py38"}
          - {python-version: "3.9", toxenv: "py39"}
          - {python-version: "3.10", toxenv: "py310"}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.cfg.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.cfg.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip ${{ matrix.build-system }} tox

      - name: Run Tox
        run: tox -e ${{ matrix.cfg.toxenv }}-smoke-cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.cfg.python-version ==  ${{ env.MAIN_PYTHON_VERSION }}

  build-library:
    name: Build library
    runs-on: ubuntu-latest
    needs: [tests, doc-deploy-stable]
    steps:
      - name: Build library source and wheel artifacts
        uses: pyansys/actions/build-library@main
        with:
          library-name: ${{ env.LIBRARY_NAME }}

  release-pypi-public:
    name: Release to public PyPI
    runs-on: ubuntu-latest
    needs: [build-library]
    steps:
      - name: Release to the public PyPI repository
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: pyansys/actions/release-pypi-public@main
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYPI_TOKEN }}

  release-gitub:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: [build-library]
    steps:
      - name: "Release to GitHub"
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: pyansys/actions/release-github@main
        with:
          library-name: ${{ env.LIBRARY_NAME }}
