name: Trigger end-to-end tests for solution templates
on:
  pull_request:
    paths:
      - 'src/ansys/templates/python/solution/**'
      - 'src/ansys/templates/python/osl_solution/**'

jobs:

  solutions-e2e-tests:
    name: Trigger solutions e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: github workflow dispatch
        shell: bash
        run: |
          curl -L \
          -X POST \
          -H 'Accept: application/vnd.github+json' \
          -H "Authorization: Bearer ${{ secrets.ANSYS_SOLUTIONS_E2E_TESTS }}"\
            "https://api.github.com/repos/Solution-Applications/solution-templates-end-to-end-testing/actions/workflows/_ansys-templates-remote-ci.yml/dispatches" \
            -d '{"ref":"refs/heads/main", "inputs":{"ansys_templates_sha": "${{ github.event.pull_request.head.sha }}"}}'