name: Templates Python
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:

  tests:
    name: Test ${{ matrix.cfg.template }} in Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]
        include:

          - python-version: "3.7"
            toxenv: py37-keep-output

          - python-version: "3.10"
            toxenv: py310-keep-output

        cfg:
          # All pybasic template tests
          - {template: "pybasic", outdir: "pybasic0/pybasic"}
            
          # All pybasic template tests
          - {template: "pyansys", outdir: "pyansys0/pyproduct-library"}

          # All pyansys_advanced template tests
          - {template: "pyansys_advanced", build-system: "flit", outdir: "pyansys_a0/pyproduct-library"}
          - {template: "pyansys_advanced", build-system: "poetry", outdir: "pyansys_a1/pyproduct-library"}
          - {template: "pyansys_advanced", build-system: "setuptools", outdir: "pyansys_a2/pyproduct-library"}

      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bake ${{ matrix.template }}
        run: |
          python -m pip install --upgrade pip tox

      - name: Run Tox
        run: |
          export TEMPLATE=${{ matrix.template }}
          tox -e ${{ matrix.toxenv }}-template

      - name: Install baked project
        run: |
          cd "output/test_template_python_${{ matrix.cfg.outdir }}"
          python -m pip install -e .
          python -m pip install -r requirements_tests.txt
          pytest tests -vvv
