name: Templates Python
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:

  tests:
    name: Test ${{ matrix.template }} in Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]
        template: ["pybasic", "pyansys", "pyansys_advanced"]
        include:

          - python-version: "3.7"
            toxenv: py37-keep-output

          - python-version: "3.10"
            toxenv: py310-keep-output

      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bake ${{ matrix.template }}
        run: |
          python -m pip install --upgrade pip tox

      - name: Run Tox
        run: |
          export TEMPLATE=${{ matrix.template }}
          tox -e ${{ matrix.toxenv }}-template
